# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNASDKTinkoff' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNASDKTinkoff
  pod 'CardIO'
  pod 'ASDKCore', :podspec =>  "https://raw.githubusercontent.com/TinkoffCreditSystems/tinkoff-asdk-ios/master/ASDKCore.podspec"
  pod 'ASDKUI', :podspec =>  "https://raw.githubusercontent.com/TinkoffCreditSystems/tinkoff-asdk-ios/master/ASDKUI.podspec"

end
